language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
notifications:
  email: false
script:
  - npm run syntax
  - npm test
after_script:
  - npm run coveralls
env:
  global:
    - DEBUG=1
    - secure: "e99iu0TysSJ34X1O209bMJP94shPBHLiNICfaEUWdnW1H8A63g5G21wRknVTokZ6ltH5rh9Zm5c90zLI8SPkio+0TaSym8t8mqXzH8nTLCy0cQPHss3vyOCoa1Iov5i33EbHeRuVwhstJMoh/MN1GQ9IkPCIN97BjkzJ8+mILk0="
    - secure: "F1nqhRcc9GK1vSVhRUtG6PJkObhL8pqBEwWDXYceOsSHZTlHQplmY7ifin1F1nx+1qu543Z1c7Y76GSPp9n+8dlcQYACraOsqi61A9dzxdnhAbDjiEMxgORhEdHGtOvP+jxwqByo+px9RuYiDF/qMQSM2XPL3CuyXN4VX3Y9BpQ="
    - secure: " Zt9L4pg2oiHyDJZOHQnxc1LbrmjyQrP7v2LrRQmgxqBFTdh5WIiXIOAGzy1lSvCm2+LhxFNyRQ7dOT3X7my32Xkb//nV629qcjrNYaRbHb9mcc6XaCeE9XK3jn7ovDYwhQKLxMWFRrqTk/0mUBzZHT2O/LG2FJVycG6v9lXiaaU="
    - secure: "JUTQQam/WwOAYxePUKD15OcA21MH3fZ+sny3ES8KL11XTLZ0x6yhSCaGliHhMujFBZda3SPvwWF2+0k3u4Z86hs9bzdxInhc0rqsvjs78ysOei2lSq/OklYdn9ePFg4sYAcxrvUsP3zWWEnMLhYpuQ42kWF2lxWNCt6zpSCz2SY="
    - secure: "kuiBjxu9x8sj97B6nBRsogUVT2sEsQr5AOOjgHGZQkRsIcD2PyyeMXLuNgEc+InUJI1IKahjMPqaXLYnLRLeZ9T5zO0zwI6vd7h28Q5O4c5umHMoWVPTOCVdQ/b7zubiH5CZST2OOPMLZx3FRpgBz0kuBHycOjZJxhhZI7b1W8U="
